a_crm/urls.py
from django.conf.urls import url
from django.urls import path

from .views import *


urlpatterns = [
    
    path('test/<str:bla>/', test, name='test'),

    # path('lst', Lst.as_view(), name='lst'),

    # path('itm/<int:itm_id>/che', Che.as_view(), name='che'),
    path('itm/<int:itm_id>/che', che, name='che'),
    
    # path('itm/<int:itm_id>/remfile', remfile, name='remfile'),


    # path('', Home.as_view(), name='home'),
    
    path('lst', Lst.as_view(), name='lst'),
    # path('lst', lst, name='lst'),

    path('itm/<int:itm_id>', Itm.as_view(), name='itm'),
    path('itm/<int:itm_id>/rem', Rem.as_view(), name='rem'),

    path('itm/add', Add.as_view(), name='add'),
    
    path('invoice/<int:itm_id>', invoice, name='invoice'),


    
    # path('inf/', InfLst.as_view(), name='inflst'),
    # path('inf/<int:inf_id>', InfOne.as_view(), name='infone'),




    # path('lgn', Lgn.as_view(), name='lgn'),
    # path('rgt', Rgt.as_view(), name='rgt'),
    # path('per', Per.as_view(), name='per'),
    # path('lgt', lgt, name='lgt'),

]

crm/urls.py
from home.views import pageNotFound
from django.conf.urls import handler400
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

from a_crm.views import * 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('crm/', include('a_crm.urls')),
    path('per/', include('b_per.urls')),
    path('rpt/', include('c_rpt.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

a_crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from django.conf import settings


class Items(models.Model):

    phot_with = models.BooleanField(default=False, verbose_name="С фото?", null=True, blank=True)
    
    surn =      models.CharField(max_length=255, verbose_name="Фамилия")
    name =      models.CharField(max_length=255, verbose_name="Имя",      null=True, blank=True)
    midn =      models.CharField(max_length=255, verbose_name="Отчество", null=True, blank=True)
    
    date_birt = models.DateField(verbose_name="Дата рождения умершего", null=True, blank=True)
    date_deat = models.DateField(verbose_name="Дата смерти умершего",   null=True, blank=True)
    date_fune = models.DateField(verbose_name="Дата выдачи заказа",     null=True, blank=True)
    
    code =      models.ForeignKey('Codes',    on_delete=models.PROTECT, verbose_name="Код заказа", null=True, blank=True)
    colo =      models.ForeignKey('Colors',   on_delete=models.PROTECT, verbose_name="Цвет рамки", null=True, blank=True)
    fast =      models.ForeignKey('Fasts',    on_delete=models.PROTECT, verbose_name="Крепление",  null=True, blank=True)
    posi =      models.ForeignKey('Position', on_delete=models.PROTECT, verbose_name="Ориентация", null=True, blank=True)
    addr =      models.ForeignKey('Address',  on_delete=models.PROTECT, verbose_name="Адрес",      null=True, blank=True)
    
    numb =      models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Количество",    null=True, blank=True)

    desc =      models.TextField(verbose_name="Рекомендации по обработке", blank=True, help_text='help_text')
    
    phot_natu = models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Фото",                null=True, blank=True)
    phot_reto = models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Фото ретушированное", null=True, blank=True)
        
        
    mana =      models.ForeignKey(User, on_delete=models.PROTECT, related_name = 'mana', verbose_name="Менеджер", null=True, blank=True)

    agre =      models.BooleanField(default=False, verbose_name="Согласовано")
    fini =      models.BooleanField(default=False, verbose_name="Закончен")
    
    auth =      models.ForeignKey(User, on_delete=models.PROTECT, related_name = 'auth', verbose_name="Агент")
    time_crea = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_upda = models.DateTimeField(auto_now=True,     verbose_name="Время изменения")

    def __str__(self):
        return self.surn

    def get_absolute_url(self):
        return reverse('itm', kwargs={'itm_id': self.pk})

    class Meta:
        verbose_name = 'Заказы'
        verbose_name_plural = 'Заказы'
        ordering = ['-time_crea', 'surn']

    def delete(self, *args, **kwargs):
        super(Items, self).delete(*args, **kwargs)
        try:
            storage, path = self.phot_natu.storage, self.phot_natu.path
            storage.delete(path)
        except:
            pass
        try:
            storage, path = self.phot_reto.storage, self.phot_reto.path
            storage.delete(path)
        except:
            pass


class Address(models.Model):
    titl = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.CharField(max_length=255, verbose_name="slug", blank=True)
    desc = models.TextField(verbose_name="Описание", blank=True)
    time_crea = models.DateTimeField(auto_now_add=True)
    time_upda = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.titl
        
    class Meta:
        verbose_name = 'Адреса'
        verbose_name_plural = 'Адреса'
        ordering = ['titl']


class Codes(models.Model):

    titl = models.CharField(max_length=255, verbose_name="Заголовок")
    
    slug = models.CharField(max_length=255, verbose_name="slug",                       null=True, blank=True)
    desc = models.TextField(verbose_name="Описание",                                   null=True, blank=True)
    
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена",   null=True, blank=True)
    
    word = models.CharField(max_length=255, verbose_name="Текстовое отображение цены", null=True, blank=True)

    phot = models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Фото",         null=True, blank=True)
    
    time_crea = models.DateTimeField(auto_now_add=True)
    time_upda = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.titl
        
    # def get_absolute_url(self):
    #     return reverse('tlsitm', kwargs={'slug': 'cds', 'id': self.pk})

    class Meta:
        verbose_name = 'Коды'
        verbose_name_plural = 'Коды'
        ordering = ['titl']


class Colors(models.Model):
    titl = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.CharField(max_length=255, verbose_name="slug", blank=True)
    desc = models.TextField(verbose_name="Описание", blank=True)
    code = models.ForeignKey('Codes', on_delete=models.PROTECT, verbose_name="Код заказа")
    time_crea = models.DateTimeField(auto_now_add=True)
    time_upda = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.titl
        
    # def get_absolute_url(self):
    #     return reverse('tlsitm', kwargs={'slug': 'clr', 'id': self.pk})

    class Meta:
        verbose_name = 'Цвета'
        verbose_name_plural = 'Цвета'
        ordering = ['titl']


class Fasts(models.Model):
    titl = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.CharField(max_length=255, verbose_name="slug", blank=True)
    desc = models.TextField(verbose_name="Описание", blank=True)
    code = models.ForeignKey('Codes', on_delete=models.PROTECT, verbose_name="Код заказа")
    time_crea = models.DateTimeField(auto_now_add=True)
    time_upda = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.titl
        
    # def get_absolute_url(self):
    #     return reverse('tlsitm', kwargs={'slug': 'fst', 'id': self.pk})

    class Meta:
        verbose_name = 'Крепеж'
        verbose_name_plural = 'Крепеж'
        ordering = ['titl']


class Position(models.Model):
    titl = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.CharField(max_length=255, verbose_name="slug", blank=True)
    desc = models.TextField(verbose_name="Описание", blank=True)
    code = models.ForeignKey('Codes', on_delete=models.PROTECT, verbose_name="Код заказа")
    time_crea = models.DateTimeField(auto_now_add=True)
    time_upda = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.titl
        
    # def get_absolute_url(self):
    #     return reverse('home', kwargs={'slug': 'pst', 'id': self.pk})

    class Meta:
        verbose_name = 'Позиция'
        verbose_name_plural = 'Позиция'
        ordering = ['titl']

a_crm/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.db.models.fields import EmailField
from django.db.models.fields.files import FileField
from django.forms import ModelForm, TextInput, Textarea, widgets
from django.contrib.auth.models import User

from django.conf import settings
from django.http import request

from .models import *

from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

class NewClearableFileInput(widgets.ClearableFileInput):
    template_name = 'django/forms/widgets/new_file_input.html'
    
    def xx(self):
        return '10'


class NewCheckboxInput(widgets.CheckboxInput):
    template_name = 'django/forms/widgets/new_checkbox.html'

    def get_context(self, name, value, attrs, **kwargs):
        context = super().get_context(name, value, attrs, **kwargs)
        context['widget']['on'] = 'В работе'
        context['widget']['of'] = 'Взять в работу'
        return context


class ItmForm(ModelForm):

    phot_with = forms.BooleanField(label='Без фото', required=False, initial=False)

    surn = forms.CharField(label='Фамилия умершего',  widget=TextInput(attrs={'class': 'inp', 'placeholder': 'Фамилия'}))
    name = forms.CharField(label='Имя умершего',      widget=TextInput(attrs={'class': 'inp', 'placeholder': 'Имя'}), required=False)
    midn = forms.CharField(label='Отчество умершего', widget=TextInput(attrs={'class': 'inp', 'placeholder': 'Отчество'}), required=False)
    
    date_birt = forms.DateField(label='Дата рождения умершего', widget=TextInput(attrs={'class': 'inp dates', 'placeholder':'Введите дату' }))
    date_deat = forms.DateField(label='Дата смерти умершего',   widget=TextInput(attrs={'class': 'inp dates', 'placeholder':'Введите дату' }), required=False)
    date_fune = forms.DateField(label='Дата выдачи заказа',     widget=TextInput(attrs={'class': 'inp dates', 'placeholder':'Введите дату' }), required=False)
    
    code = forms.ModelChoiceField(label='Код', queryset=Codes.objects.all(), widget=forms.RadioSelect(attrs={'class': 'rds'}), required=False)
    colo = forms.ModelChoiceField(label='Цвет рамки',     queryset=Colors.objects.all(),   widget=forms.Select(attrs={'class': 'sel'}),      required=False)
    fast = forms.ModelChoiceField(label='Крепёж',         queryset=Fasts.objects.all(),    widget=forms.Select(attrs={'class': 'sel'}),      required=False)
    posi = forms.ModelChoiceField(label='Ориентация',     queryset=Position.objects.all(), widget=forms.Select(attrs={'class': 'sel'}),      required=False)
    addr = forms.ModelChoiceField(label='Адрес доставки', queryset=Address.objects.all(),  widget=forms.Select(attrs={'class': 'sel'}),      required=False)

    numb = forms.DecimalField(label='Количество', widget=forms.NumberInput(attrs={'class': 'inp', 'min':1,'max': '666'}), required=False, initial=1)
    
    desc = forms.CharField(label='Рекомендации по ретуши фотографии',  widget=forms.Textarea(attrs={'class': 'txta', 'placeholder': 'Если вы не заполнили этот раздел, то обработка изображения выполняется в соответствии с стандартами подрядчика'}), required=False, help_text='Если вы не заполнили этот раздел, то обработка изображения выполняется в соответствии с стандартами подрядчика')

    phot_natu = forms.ImageField(label='Загрузить фотографию умершего', widget=NewClearableFileInput(attrs={'class': 'fil'}), required=False)
    phot_reto = forms.ImageField(label='Фото ретушированное',           widget=NewClearableFileInput(attrs={'class': 'fil'}), required=False)
    
    mana_chec = forms.BooleanField(label='Менеджер',    widget=NewCheckboxInput(attrs={'class': 'chx'}), required=False, initial=False)
    
    agre = forms.BooleanField(label='Согласовано', widget=widgets.CheckboxInput(attrs={'class': 'chx'}), required=False, initial=False)  
    fini = forms.BooleanField(label='Выполнен',    widget=widgets.CheckboxInput(attrs={'class': 'chx'}), required=False, initial=False)

    class Meta:
        model = Items
        fields = [
            'phot_with', 
            'surn', 'name', 
            'midn', 
            'date_birt', 
            'date_deat', 
            'date_fune', 
            'code', 
            'numb', 
            'colo', 
            'fast', 
            'posi', 
            'addr', 
            'phot_natu', 
            'phot_reto', 
            'desc',
            'agre',
            'fini',
            'mana',
        ]


class SearForm(forms.Form):
    agent = forms.CharField(widget=TextInput(attrs={'placeholder': 'Поиск по фамлии агента'}))










# class ItmFormChenAge(ItmForm):

#     class Meta:
#         model = Items
#         fields = ['phot_with', 'surn', 'name', 'midn', 'date_birt', 'date_deat', 'date_fune', 'code', 'numb', 'colo', 'fast', 'posi', 'addr', 'phot_natu', 'desc']


# class ItmFormChenMan(ItmForm):

    
    

#     class Meta:
#         model = Items
#         fields = ['phot_with', 'surn', 'name', 'midn', 'date_birt', 'date_deat', 'date_fune', 'code', 'numb', 'colo', 'fast', 'posi', 'addr', 'phot_natu', 'phot_reto', 'desc', 'agre', 'fini']

a_crm/templates/a_crm/add.html
{% extends 'home/base.html' %}

{% block content %}

    <div class="span12 left">

        <h1 class="bt1">{{ title }}</h1>

        <div class="span12 tbpa">

            <form method="POST" action="{% url 'add' %}" enctype="multipart/form-data">

                <div class="error">{{ error }}</div>
                {% csrf_token %}
                {% include 'a_crm/forma.html' %}

                <div class="span12 left">
                    <button type="submit" class="btn">Отправить</button>
                </div>

            </form>
            
        </div>
    </div>
{% endblock %}

a_crm/templates/a_crm/che.html
{% extends 'home/base.html' %}

{% block content %}
    
    <div class="span12 left">

        <h1 class="bt1">{{ title }}</h1>

        <div class="span12 tbpa">
            
            <!-- {{ itm_id }}<br> -->
            <!-- {{ data }}<br> -->
            <!-- {{ datalist }}<br> -->
            <!-- {{ data.surn }}<br> -->
            <!-- {{ data.date_birt }}<br> -->
            <!-- {{ data.phot_natu }}<br> -->
            <!-- {{ data.phot_reto }}<br> -->
            <!-- {{ form }}<br> -->
            <!-- {{ data.id }}<br> -->
            <!-- {{ data.mana }}<br> -->
            <!-- {{ x }}<br> -->
            


            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="error">{{ error }}</div>
                
                {% include 'a_crm/forma.html' %}

                <div class="span12 left">
                    <div class="span3"><button type="submit" class="btn">Сохранить</button></div>
                    <div class="span9 left"><a href="{% url 'itm' itm_id %}">Вернуться не сохраняя</a></div>
                </div>
            
            </form>
            
        </div>
    
    </div>

{% endblock %}

a_crm/templates/a_crm/forma.html
{% load static %}
{% load crm_tags %}
{% is_manager as is_manager %}

<div class="span12">

    <div class="span8 leftblock">
        
        <div class="error"></div>

        {% if is_manager %}
        <div class="groups">
            {{ form.mana_chec }}
        </div>
        {% endif %}

        <div class="groups">
            <label>Фамилия умершего:</label> 
            {{ form.surn }}
        </div>
        
        <div class="groups">
            <label>Имя умершего:</label> 
            {{ form.name }}
        </div>

        <div class="groups">
            <label>Отчество умершего:</label> 
            {{ form.midn }}
        </div>

        <div class="groups">
            <label>Дата рождения умершего:</label>
            {{ form.date_birt }}
        </div>

        <div class="groups">
            <label>Дата смерти:</label>
            {{ form.date_deat }}
        </div>

        <div class="groups">
            <label>Дата выдачи заказа:</label>
            {{ form.date_fune }}
        </div>

        <div class="groups">
            <label>Код:</label>
            {{ form.code }}
        </div>

        <div class="groups">
            <label>Цвет рамки:</label>
            {{ form.colo }}
        </div>

        <div class="groups">
            <label>Крепление:</label>
            {{ form.fast }}
        </div>

        <div class="groups">
            <label>Ориентация:</label>
            {{ form.posi }}
        </div>

        <div class="groups">
            <label>Адрес доставки:</label>
            {{ form.addr }}
        </div>

        <div class="groups">
            <label>Количество:</label>
            {{ form.numb }}
        </div>

        <div class="groups">
            <label>Рекомендации по ретуши фотографии:</label>
            {{ form.desc }}
        </div>

        <div class="groups">
            <label>Согласовано:</label>
            {{ form.agre }}
        </div>

        {% if is_manager %}
        <div class="groups">
            <label for="id_fini">Завершено:</label>
            {{ form.fini }}
        </div>
        {% endif %}

    </div>
    
    <div class="span4 rightblock">

        <div class="groups">
            {{ form.phot_natu }}
        </div>

        {% if is_manager %}
        <div class="groups">
            {{ form.phot_reto }}
        </div>
        {% endif %}

    </div>

</div>

a_crm/templates/a_crm/invoice.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

    <div class="span12 inv">
        
        <h1 class="bt1">{{ title }}</h1>
        
        {% if link %}
        <div class="span12">
            <br>
            <a href="../../{{ link }}" download="" class="down">Скачать накладную</a>
        </div>
        {% endif %}
        
    </div>

{% endblock %}

a_crm/templates/a_crm/itm.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

    <div class="span12 itm">
        
        <h1 class="bt1">{{ title }}</h1>

        {% if info %}
        
        <div class="span12 tool center">

            <div class="span6 left">

                <div class="fini">
                    {% if info.fini %}
                    <img src="{% static 'home/images/finish.png' %}" alt="">
                    {% else %}
                    <img src="{% static 'home/images/process.png' %}" alt="">
                    {% endif %}
                </div>

                <div class="mana">Менеджер: {{ mana }}</div>

            </div>

            <div class="span6 right">
                <a href="{% url 'invoice' info.id %}" class="too">
                    Накладная
                </a>
                <a href="{% url 'che' info.id %}"     class="too">
                    Изменить
                </a>
                <a href="{% url 'rem' info.id %}"     class="rem">
                    Удалить
                </a>
            </div>

        </div>

        <div class="span8 txt">

            <div class="wrap span12">
                <div class="span12 label">ФИО</div>
                <div class="span12 info">{{ info.surn }} {{ info.name }} {{ info.midn }}</div>
            </div>

            <div class="wrap span12 birt">
                <div class="span12 label">Дата рождения умершего</div>
                <div class="span12 info">{{ info.date_birt|date:"d.m.Y" }}</div>
            </div>
            
            <div class="wrap span12 deat">
                <div class="span12 label">Дата смерти умершего</div>
                <div class="span12 info">
                    {% if info.date_deat %}
                        {{ info.date_deat|date:"d.m.Y" }}
                    {% else %}
                        не выбрано
                    {% endif %}
                </div>
            </div>
            
            <div class="wrap span12">
                <div class="span12 label">Дата выдачи заказа</div>
                <div class="span12 info">
                    {% if info.date_fune %}
                        {{ info.date_fune|date:"d.m.Y" }}
                    {% else %}
                        не выбрано
                    {% endif %}
                </div>
            </div>
            
            <div class="wrap span12">
                <div class="span12 label">Количество</div>
                <div class="span12 info">{{ info.numb }}</div>
            </div>

            <div class="wrap span12">
                <div class="span12 label">Код</div>
                <div class="span12 info">{{ info.code }}</div>
            </div>

            <div class="wrap span12">
                <div class="span12 label">Цвет</div>
                <div class="span12 info">{{ info.colo }}</div>
            </div>

            <div class="wrap span12">
                <div class="span12 label">Крепёж</div>
                <div class="span12 info">{{ info.fast }}</div>
            </div>

            <div class="wrap span12">
                <div class="span12 label">Ориентация</div>
                <div class="span12 info">{{ info.posi }}</div>
            </div>

            <div class="wrap span12">
                <div class="span12 label">Адрес доставки</div>
                <div class="span12 info">{{ info.addr }}</div>
            </div>

            <div class="wrap span12">
                <div class="span12 label">Рекомендации</div>
                <div class="span12 info">{{ info.desc }}</div>
            </div>

        </div>

        <div class="span4 pic">
            <div>
                {% if info.phot_natu %}
                    <img class="imgs" src="{{ info.phot_natu.url }}" alt="">
                    <a href="{{ info.phot_natu.url }}" target="_blank" download="" title="Скачать файл" class="down" onclick='confirm("Скачать файл?");'>Скачать файл</a>
                {% else %}
                    <img class="imgs" src="{% static 'home/images/no-photos.png' %}" alt="">
                {% endif %}
            </div>
            <div>
                {% if info.phot_reto %}
                    <img class="imgs" src="{{ info.phot_reto.url }}" alt="">
                    <a href="{{ info.phot_reto.url }}" target="_blank" download="" title="Скачать файл" class="down" onclick='confirm("Скачать файл?");'>Скачать файл</a>
                {% else %}
                    <img class="imgs" src="{% static 'home/images/no-photos.png' %}" alt="">
                {% endif %}
            </div>        
        </div>

        <div class="span12 sign">
            <div class="span4">
                <span>Агент: </span><span>{{ auth }}</span>
            </div>
            <div class="span4">
                <span>Менеджер: </span><span>{{ mana }}</span>
            </div>                
            <div class="span4">
                <span>Дата внесения: </span><span>{{ info.time_crea }}</span>
            </div>   
            
        </div>

        {% else %}
            <p>No info</p>
        {% endif %}

    </div>

{% endblock %}

a_crm/templates/a_crm/lst.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

    <div class="span12 lst">

        <h1 class="bt1">{{ title }} ({{ len }})</h1>

        <div class="span12">
            
            <div class="span6 uptool left">
                {% if is_manager %}
                    {% include 'a_crm/search.html' %}
                {% endif %}
            </div>
    
            <div class="span6 uptool right">
                <a href="{% url 'lst' %}" class="too">
                    Все
                </a>
                <a href="{% url 'lst' %}?fini=False" class="too">
                    В работе
                </a>
                <a href="{% url 'lst' %}?fini=True" class="too">
                    Законченные
                </a>
            </div>

        </div>






        {% if data %}
            {% for d in data %}

                <div class="row center">
                    <div class="fini left">
                        {% if d.fini %}
                            <img src="{% static 'home/images/finish.png' %}" alt="">
                        {% else %}
                            <img src="{% static 'home/images/process.png' %}" alt="">
                        {% endif %}
                    </div>
                    <div class="id left">{{ d.id }}</div>
                    <div class="titl left"><a href="{{ d.get_absolute_url }}">{{ d.surn }} {{ d.name }} {{ d.midn }}</a></div>
                    
                    <div class="auth left">Агент: {{ d.auth.last_name }}</div>
                    
                    <div class="mana left">Менеджер: 
                        {% if d.mana %}
                            {{ d.mana.last_name }}
                        {% else %}
                            -
                        {% endif %}
                    </div>
                    
                    <div class="tool right">
                        {% if d.phot_natu %}
                        <a href="{{ d.phot_natu.url }}"  download="" onclick='confirm("Скачать фото?");'>
                            <img class="mini" src="{% static 'home/images/imag.png' %}" alt="Скачать фото" title="Скачать фото">
                        </a>
                        {% endif %}
                        <a href="{% url 'itm' d.id %}">
                            <img class="mini" src="{% static 'home/images/look.png' %}" alt="Просмотр" title="Просмотр">
                        </a>
                        <a href="{% url 'che' d.id %}">
                            <img class="mini" src="{% static 'home/images/edit.png' %}" alt="Редактировать" title="Редактировать">
                        </a>
                    </div>
                </div>
                
            {% endfor %}
        {% else %}
            <div class="span12 no">Результатов не найдено</div>
        {% endif %}
    
    </div>

{% endblock %}

a_crm/templates/a_crm/rem.html
{% extends 'home/base_empty.html' %}

{% block content %}

    
        

<div class="span5 box">

    <h1 class="bt1">Подтверждение удаления</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div class="notice">Вы действительн хотите удалить "{{ object }}"?</div>

        <div class="span12 center">
            <div class="span6 left"><button type="submit" class="btn">Да, хочу</button></div>
            <div class="span6 right"><a href="{% url 'itm' object.id %}">Нет, вернуться в карточку</a></div>
        </div>
        
    </form>

</div>

{% endblock %}

a_crm/templates/a_crm/remfile.html
{% extends 'home/base_empty.html' %}

{% block content %}

    
        

<div class="span5 box">

    <h1 class="bt1">Подтверждение удаления</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div class="notice">Вы действительн хотите удалить файл"?</div>

        <div class="span12 center">
            <div class="span6 left"><button type="submit" class="btn">Да, хочу</button></div>
            <div class="span6 right"><a href="{% url 'itm' object.id %}">Нет, вернуться в карточку</a></div>
        </div>
        
    </form>

</div>

{% endblock %}

a_crm/templates/a_crm/search.html
{% load static %}
{% load crm_tags %}
{% is_manager as is_manager %}



<form method="POST" action="{% url 'lst' %}" method="GET" class="searform">
    {% csrf_token %}
    {{ searform.agent }}
    <button type="submit" class="">Искать</button>
</form>

a_crm/templates/a_crm/test.html
{% extends 'home/base_empty.html' %}

{% block content %}

    <div class="span12 left">

        <h1 class="bt1">{{ title }}</h1>

        <div class="span12 tbpa">
            {{ data }}
        </div>
    </div>
{% endblock %}